# Generated by Django 4.0.5 on 2022-06-19 13:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('m_menus', '0003_globalmenu_site_name_alter_globalmenu_munus'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmenu',
            name='footer',
            field=wagtail.fields.StreamField([('Page', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('href', wagtail.blocks.PageChooserBlock())])), ('Item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('href', wagtail.blocks.PageChooserBlock())]))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
