version: "3.9"
services:
  app:
    build:
      context: srv/
    env_file:
      - .env_docker
    volumes:
      - ./srv/project:/app:ro
      - /www/media:/media:delegated,rw
      - /www/static:/static:delegated,rw
    depends_on:
      - postgres

  postgres:
    container_name: cms_pg_blog
    image: postgres
    volumes:
      - ./data/pg_cms:/var/lib/postgresql/data:delegated,rw
    env_file:
      - .env_docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER " ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx_simple:
    image: nginx:stable
    volumes:
      - ./conf/conf.d/simple.conf:/etc/nginx/nginx.conf:ro
      - /www/media:/media:ro
      - /www/static:/static:ro
    ports:
      - "80:80"
    depends_on:
      - app
