version: "3.9"
services:
  app:
    build:
      context: srv/
    env_file:
      - .env_docker
    ports:
      - "80:80"
    volumes:
      - ./srv/project:/app:ro
    depends_on:
      - postgres

  postgres:
    container_name: cms_pg_blog
    image: postgres
    volumes:
      - ./data/pg_cms:/var/lib/postgresql/data:delegated,rw
    env_file:
      - .env_docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER " ]
      interval: 5s
      timeout: 5s
      retries: 5
