version: "3"
services:
  app:
    container_name: cms_wagtail
    build:
      context: srv/
    ports:
      - "80:80"
    env_file:
      - .env_docker
    volumes:
      - media_data:/app/media
      - static:/app/static
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 3

  postgres:
    container_name: cms_pg_blog
    image: postgres
    volumes:
      - pg_cms:/var/lib/postgresql/data
    env_file:
      - .env_docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER " ]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "dertylupos@mail.ru"
    ports:
      - "443:443"
    volumes:
      - ./conf/conf.d:/etc/nginx/user.conf.d:ro
    links:
      - "app:django"

