version: "3"
services:
  app:
    container_name: cms_wagtail
    build:
      context: srv/
    ports:
      - "80:80"
    env_file:
      - .env_docker
    volumes:
      - media_data:/app/media
      - static:/app/static
    command: tail -f /dev/null
    depends_on:
      - postgres

  postgres:
    container_name: cms_pg_blog
    image: postgres
    volumes:
      - pg_cms:/var/lib/postgresql/data
    env_file:
      - .env_docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER " ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  static:
    driver: local
  media:
    driver: local
  media_data:
  pg_cms: