version: '3.9'

services:
  nginx:
    image: pagespeed/nginx-pagespeed:stable
    restart: unless-stopped
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
      - /www/media:/media:ro
      - /www/static:/static:ro
    ports:
      - "80:80"
      - "443:443"
    external_links:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

