version: "3"
services:
  app:
    container_name: cms_wagtail
    build:
      context: srv/project
    ports:
      - "80:3000"
    env_file:
      - .env_docker
    volumes:
      - media_data:/app/media
      - static:/app/static
    depends_on:
      - postgres
    networks:
      backend:
        ipv4_address: 172.15.0.2
    command: ["/bin/sh","./start.sh"]

  postgres:
    container_name: cms_pg
    image: postgres
    volumes:
      - pg_cms:/var/lib/postgresql/data
    env_file:
      - .env_docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER " ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      backend:
        ipv4_address: 172.15.0.3

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
          gateway: 172.15.0.1

volumes:
  static:
    driver: local
  media:
    driver: local
  media_data:
  pg_cms: